=== reed38/Generating_yolo_dataset_and_training_blender_ultralytics_yoloV8/image_generation/conf/config_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "id": {
                "type": "string"
            },
            "classe": {
                "type": "integer"
            },
            "image_width": {
                "type": "integer"
            },
            "image_height": {
                "type": "integer"
            },
            "render_percentage": {
                "type": "integer"
            },
            "samples_number": {
                "type": "integer"
            },
            "object_path": {
                "type": "string"
            },
            "render_number": {
                "type": "integer"
            },
            "radiusVariation": {
                "type": "object",
                "properties": {
                    "min": {
                        "type": "integer"
                    },
                    "max": {
                        "type": "integer"
                    }
                },
                "required": ["min", "max"]
            },
            "angleBetaVariation": {
                "type": "object",
                "properties": {
                    "min": {
                        "type": "integer"
                    },
                    "max": {
                        "type": "integer"
                    }
                },
                "required": ["min", "max"]
            },
            "angleTetaVariation": {
                "type": "object",
                "properties": {
                    "min": {
                        "type": "integer"
                    },
                    "max": {
                        "type": "integer"
                    }
                },
                "required": ["min", "max"]
            },
            "angleRohVariation": {
                "type": "object",
                "properties": {
                    "min": {
                        "type": "integer"
                    },
                    "max": {
                        "type": "integer"
                    }
                },
                "required": ["min", "max"]
            },
            "heightVariation": {
                "type": "object",
                "properties": {
                    "min": {
                        "type": "integer"
                    },
                    "max": {
                        "type": "integer"
                    }
                },
                "required": ["min", "max"]
            }
        },
        "required": ["id", "classe", "image_width", "image_height", "render_percentage", "samples_number", "object_path", "render_number", "radiusVariation", "angleBetaVariation", "angleTetaVariation", "angleRohVariation", "heightVariation"]
    }
}

=== reed38/Generating_yolo_dataset_and_training_blender_ultralytics_yoloV8/image_generation/conf/config.json
[
    {
        "id": "zone_1_terrain_sport",
        "classe":0,
        "image_width": 800,
        "image_height": 600,
        "render_percentage": 100,
        "samples_number": 5,
        "object_path": "zone_1_terrain_athle.dae",
        "render_number": 50,
        "radiusVariation": {"min": 0, "max": 150},
        "angleBetaVariation": {"min": -2, "max": 2},
        "angleTetaVariation": {"min": -5, "max": 5},
        "angleRohVariation": {"min": 0, "max": 360},
        "heightVariation": {"min": 20, "max": 300}
    },
    {
        "id": "zone_2_taxi",
        "classe":1,
        "image_width": 800,
        "image_height": 600,
        "render_percentage": 100,
        "samples_number": 30,
        "object_path": "zone_2_taxi.dae",
        "render_number": 50,
        "radiusVariation": {"min": 0, "max": 150},
        "angleBetaVariation": {"min": -2, "max": 2},
        "angleTetaVariation": {"min": -5, "max": 5},
        "angleRohVariation": {"min": 0, "max": 360},
        "heightVariation": {"min": 20, "max": 300}
    },
    {
        "id": "zone_3_planete_science",
        "classe":2,
        "image_width": 800,
        "image_height": 600,
        "render_percentage": 100,
        "samples_number": 30,
        "object_path": "zone_3_planete_science.dae",
        "render_number": 50,
        "radiusVariation": {"min": 0, "max": 150},
        "angleBetaVariation": {"min": -2, "max": 2},
        "angleTetaVariation": {"min": -5, "max": 5},
        "angleRohVariation": {"min": 0, "max": 360},
        "heightVariation": {"min": 20, "max": 300}
    },
    {
        "id": "zone_4_jeux",
        "classe":3,
        "image_width": 800,
        "image_height": 600,
        "render_percentage": 100,
        "samples_number": 30,
        "object_path": "zone_4_jeux.dae",
        "render_number": 50,
        "radiusVariation": {"min": 0, "max": 150},
        "angleBetaVariation": {"min": -2, "max": 2},
        "angleTetaVariation": {"min": -5, "max": 5},
        "angleRohVariation": {"min": 0, "max": 360},
        "heightVariation": {"min": 20, "max": 300}
    },
    {
        "id": "zone_5_decollage_atterissage",
        "classe":4,
        "image_width": 800,
        "image_height": 600,
        "render_percentage": 100,
        "samples_number": 30,
        "object_path": "zone_atterissage_decollage.dae",
        "render_number": 50,
        "radiusVariation": {"min": 0, "max": 150},
        "angleBetaVariation": {"min": -2, "max": 2},
        "angleTetaVariation": {"min": -5, "max": 5},
        "angleRohVariation": {"min": 0, "max": 360},
        "heightVariation": {"min": 20, "max": 300}
    },
    {
        "id": "blue_object",
        "classe":5,
        "image_width": 800,
        "image_height": 600,
        "render_percentage": 100,
        "samples_number": 30,
        "object_path": "blue_object.dae",
        "render_number": 50,
        "radiusVariation": {"min": 0, "max": 150},
        "angleBetaVariation": {"min": -2, "max": 2},
        "angleTetaVariation": {"min": -5, "max": 5},
        "angleRohVariation": {"min": 0, "max": 360},
        "heightVariation": {"min": 20, "max": 300}
    },
    {
        "id": "yellow_object",
        "classe":6,
        "image_width": 800,
        "image_height": 600,
        "render_percentage": 100,
        "samples_number": 30,
        "object_path": "yellow_object.dae",
        "render_number": 50,
        "radiusVariation": {"min": 0, "max": 150},
        "angleBetaVariation": {"min": -2, "max": 2},
        "angleTetaVariation": {"min": -5, "max": 5},
        "angleRohVariation": {"min": 0, "max": 360},
        "heightVariation": {"min": 20, "max": 300}
    },
    {
        "id": "red_object",
        "classe":7,
        "image_width": 800,
        "image_height": 600,
        "render_percentage": 100,
        "samples_number": 30,
        "object_path": "red_object.dae",
        "render_number": 50,
        "radiusVariation": {"min": 0, "max": 150},
        "angleBetaVariation": {"min": -2, "max": 2},
        "angleTetaVariation": {"min": -5, "max": 5},
        "angleRohVariation": {"min": 0, "max": 360},
        "heightVariation": {"min": 20, "max": 300}
    }

]
